// flow-typed signature: 526cca82237ad10acd80b6f2c55d7615
// flow-typed version: <<STUB>>/d3-interpolate-path_v2.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-interpolate-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-interpolate-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-interpolate-path/build/d3-interpolate-path' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/build/d3-interpolate-path.min' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/docs/d3-interpolate-path' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/docs/examples' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/docs/v1/d3-interpolate-path-v1.1.1' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/docs/v1/examples' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/src/interpolatePath' {
  declare module.exports: any;
}

declare module 'd3-interpolate-path/src/split' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-interpolate-path/build/d3-interpolate-path.js' {
  declare module.exports: $Exports<'d3-interpolate-path/build/d3-interpolate-path'>;
}
declare module 'd3-interpolate-path/build/d3-interpolate-path.min.js' {
  declare module.exports: $Exports<'d3-interpolate-path/build/d3-interpolate-path.min'>;
}
declare module 'd3-interpolate-path/docs/d3-interpolate-path.js' {
  declare module.exports: $Exports<'d3-interpolate-path/docs/d3-interpolate-path'>;
}
declare module 'd3-interpolate-path/docs/examples.js' {
  declare module.exports: $Exports<'d3-interpolate-path/docs/examples'>;
}
declare module 'd3-interpolate-path/docs/v1/d3-interpolate-path-v1.1.1.js' {
  declare module.exports: $Exports<'d3-interpolate-path/docs/v1/d3-interpolate-path-v1.1.1'>;
}
declare module 'd3-interpolate-path/docs/v1/examples.js' {
  declare module.exports: $Exports<'d3-interpolate-path/docs/v1/examples'>;
}
declare module 'd3-interpolate-path/index' {
  declare module.exports: $Exports<'d3-interpolate-path'>;
}
declare module 'd3-interpolate-path/index.js' {
  declare module.exports: $Exports<'d3-interpolate-path'>;
}
declare module 'd3-interpolate-path/rollup.config.js' {
  declare module.exports: $Exports<'d3-interpolate-path/rollup.config'>;
}
declare module 'd3-interpolate-path/src/interpolatePath.js' {
  declare module.exports: $Exports<'d3-interpolate-path/src/interpolatePath'>;
}
declare module 'd3-interpolate-path/src/split.js' {
  declare module.exports: $Exports<'d3-interpolate-path/src/split'>;
}
